### ISSUE TITLE
I found revancify icons

### ISSUE THREAD

**Issue by girshcatt** [kastentop2005/Revancify-X#2]
You can add this icons to Telegram channels
![ic_launcher_foreground](https://github.com/kastentop2005/Revancify-X/assets/110785596/adb5252d-5ffc-4e40-930b-78a5187fd67a)
![ic_launcher](https://github.com/kastentop2005/Revancify-X/assets/110785596/2ef48922-4886-4daf-8932-3ae892af5f2b)
![ic_launcher_foreground](https://github.com/kastentop2005/Revancify-X/assets/110785596/66fa41ae-9cce-4132-ba91-ac0846c01a23)
![ic_launcher](https://github.com/kastentop2005/Revancify-X/assets/110785596/c7814e28-4f91-45a9-95e9-c8f1144bfafd)

**Comment by kastentop2005** [comment]
I'll ask decipher If I'm allowed to use them

**Comment by girshcatt** [comment]
Thanks for using this icons, i think i can close issue
