### ISSUE TITLE
Can't patch youtube

### ISSUE THREAD

**Issue by big-mak** [kastentop2005/Revancify-X#20]
Using latest revx version and patching supported YouTube version. Any ideas? ![Screenshot_20230912-171337_Termux.jpg](https://github.com/kastentop2005/Revancify-X/assets/82375998/e1282377-a937-4dc3-96b3-5464d4b3de45)

**Comment by lou-stro** [comment]
Project has been discontinued for now. Remove RevX and use the original Revancify as it has been recontinued.
