### ISSUE TITLE
How to uninstall revancify?

### ISSUE THREAD

**Issue by maclefou** [kastentop2005/Revancify-X#3]
Hi, can someone help me please i'm trying to uninstall revancify for installing revancify x but i dont know the command for it can you say me what is the command please?

**Comment by girshcatt** [comment]
I advise you to delete the data of termux and install revancify x, but if you dont want to do this, install shortcut of google files here https://play.google.com/store/apps/details?id=com.marc.files
open app, and open termux on edge panel of files, go to home folder in termux and delete two folders Revancify and revancify-data
![Screenshot_20230729_132908_Files](https://github.com/kastentop2005/Revancify-X/assets/110785596/fd8d32ab-06e5-4f63-b321-a45d82fed8c6)
![Screenshot_20230729_133039_Files](https://github.com/kastentop2005/Revancify-X/assets/110785596/3d2ad609-a11e-4fa3-bcc3-326b3839c6e4)

**Comment by lijo807** [comment]
Ok i am root so thats not a problem no more thanks!

**Comment by girshcatt** [comment]
no problem, after you problem is solved, please close the issue, because developers need only open issues :)

**Comment by TireX228** [comment]
`rm -rf Revancify` and then `rm -rf revancify-data`

**Comment by lijo807** [comment]
Ok thx

**Comment by JimZiii** [comment]
> `rm -rf Revancify` and then `rm -rf revancify-data`

For anyone reading, remember it's case sensitive on Revancify

**Comment by maclefou** [comment]
Thanks, I'll check it out.
