### ISSUE TITLE
idea to fork revancify command launcher

### ISSUE THREAD

**Issue by girshcatt** [kastentop2005/Revancify-X#4]
I found two deleted apks from decipher3114 that launch command -revancify in termux automatically, can you change something at them to launch -revx, here this 2 apks at google drive:

1. https://drive.google.com/file/d/1zNjHx1xEm3Z7Xxl-g_WCINGWPmcjJneU/view?usp=drive_link
2. https://drive.google.com/file/d/1P8UtbCFcWwt65yjL8pRcL0Sht5bmGwbT/view?usp=drive_link

P.S. all the difference at apks is icon (And sry for my bad English)

**Comment by kastentop2005** [comment]
I'll look into it once I fix all the problems
